openapi: '3.0.0'
info:
  version: 1.0.0
  title: Saikan-Shoin API
  description: API for Saikan-Shoin.
security:
  - Bearer: []
paths:
  /total-studying-hours:
    get:
      tags:
        - StudyingHour
      summary: Get total studying hour.
      description: Returns total studying hour.
      responses:
        '200':
          description: A single total studying hour
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/TotalStudyingHour'
  /month-studying-hour/{yearId}/{monthId}:
    get:
      tags:
        - StudyingHour
      summary: Get Month Studying Hour by MonthId.
      description: Returns a single Month Studying Hour
      parameters:
        - name: monthId
          in: path
          description: month id
          required: true
          schema:
            type: integer
        - name: yearId
          in: path
          description: year id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: A single Month Studying Hour
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/MonthStudyingHour'
  /today-sftudying-hours:
    get:
      tags:
        - StudyingHour
      summary: Get today studying hour.
      description: Returns today studying hour.
      responses:
        '200':
          description: A single today studying hour
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/TodayStudyingHour'

components:
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
      description: Credentials or access token for API
  schemas:
    TotalStudyingHour:
      type: object
      required:
        - id
      properties:
        id:
          type: integer
          example: 1
        total_studying_hour:
          type: integer
          example: 1348
    MonthStudyingHour:
      type: object
      required:
        - id
      properties:
        id:
          type: integer
          example: 1
        month_studying_hour:
          type: integer
          example: 120
    TodayStudyingHour:
      type: object
      required:
        - id
      properties:
        id:
          type: integer
          example: 1
        today_studying_hour:
          type: integer
          example: 3
tags:
  - name: StudyingHour
    description: Access to StudyingHour