openapi: '3.0.0'
info:
  version: 1.0.0
  title: Saikan-Shoin API
  description: API for Saikan-Shoin.
# security:
#   - Bearer: []
paths:
  /total-studying-hours/{userId}:
    get:
      tags:
        - StudyingHour
      operationId: GetTotalStudyingHour
      parameters:
        - $ref: '#/components/parameters/UserId'
      summary: Get total studying hour.
      description: Returns total studying hour.
      responses:
        '200':
          description: A single total studying hour
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/TotalStudyingHour'
  /month-studying-hour/{userId}:
    get:
      tags:
        - StudyingHour
      operationId: GetMonthStudyingHour
      summary: Get Month Studying Hour by yearId and MonthId.
      description: Returns a single Month Studying Hour
      parameters:
        - $ref: '#/components/parameters/UserId'
        - $ref: '#/components/parameters/YearId'
        - $ref: '#/components/parameters/monthId'
      responses:
        '200':
          description: A single Month Studying Hour
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/MonthStudyingHour'
  /today-studying-hours/{userId}:
    get:
      tags:
        - StudyingHour
      operationId: GetTodayStudyingHour
      summary: Get today studying hour.
      description: Returns today studying hour.
      parameters:
        - $ref: '#/components/parameters/UserId'
      responses:
        '200':
          description: A single today studying hour
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/TodayStudyingHour'

  /one-month-study-times/{userId}:
    get:
      tags:
        - StudyingHour
      operationId: GetOneMonthStudyTime
      summary: Get One Month Study Time by yearId and MonthId.
      description: Returns One Month Study Time
      parameters:
        - $ref: '#/components/parameters/UserId'
        - $ref: '#/components/parameters/YearId'
        - $ref: '#/components/parameters/monthId'
      responses:
        '200':
          description: One Month Study Time
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/OneMonthStudyTime'
components:
  # securitySchemes:
  #   Bearer:
  #     type: http
  #     scheme: bearer
  #     description: Credentials or access token for API
  parameters:
    UserId:
      name: user id
      in: path
      description: ユーザーを識別するID
      required: true
      schema:
        type: integer
        example: 1
    YearId:
      name: year id
      in: query
      required: true
      description: 年を指定する
      schema:
        type: integer
        example: 2022
    monthId:
      name: month id
      in: query
      required: true
      description: 月を指定する
      schema:
        type: integer
        example: 11
  schemas:
    TotalStudyingHour:
      type: object
      required:
        - id
        - total_studying_hour
      properties:
        id:
          type: integer
          example: 1
        total_studying_hour:
          type: integer
          example: 1348
    MonthStudyingHour:
      type: object
      required:
        - id
        - month_studying_hour
      properties:
        id:
          type: integer
          example: 1
        month_studying_hour:
          type: integer
          example: 120
    TodayStudyingHour:
      type: object
      required:
        - id
        - today_studying_hour
      properties:
        id:
          type: integer
          example: 1
        today_studying_hour:
          type: integer
          example: 3
    OneMonthStudyTime:
      type: array
      items:
        properties:
          id:
            type: integer
            example: 1
          date:
            type: integer
            example: 1
          study_hour:
            type: integer
            example: 3
tags:
  - name: StudyingHour
    description: Access to StudyingHour