version: "3.8"

services:
  front:
    build:
      context: ./
      dockerfile: ./docker/front/Dockerfile
    tty: true
    working_dir: /app
    volumes:
      - ./front:/app
      - ./api/docs/openapi:/app/openapi

  app:
    build: ./docker/php
    volumes:
      - ./api/web:/work/web

  web:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./api/web:/work/web
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    volumes:
      - ./api/db-store:/var/lib/mysql
      - ./docker/mysql:/etc/mysql/conf.d
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=web-app
      - MYSQL_USER=posse
      - MYSQL_PASSWORD=password
      - TZ=Asia/Tokyo

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=0
      - PMA_HOSTS=mysql
      - PMA_USER=posse
      - PMA_PASSWORD=password
    links:
      - mysql
    ports:
      - 1234:80

  mail:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: /tmp

  swagger-ui:
    image: swaggerapi/swagger-ui
    volumes:
      - ./api/docs/openapi/openapi.yml:/app/openapi.yml
    environment:
      SWAGGER_JSON: /app/openapi.yml
    ports:
      - 8080:8080

  api-mock:
    image: stoplight/prism:latest
    ports:
      - 4010:4010
    # make random values by -d option
    command: mock -h 0.0.0.0 -d /openapi/openapi.yml
    # command: mock -h 0.0.0.0 /openapi/openapi.yml
    volumes:
      - ./api/docs/openapi/:/openapi/
