name: AWS S3 Sync

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Build and push to Amazon S3
        run: |
          cp ./.env.prod ./.env
          yarn install
          yarn build
          yarn next export
          aws s3 sync ./out s3://portal-front-stg --delete --exact-timestamps --acl bucket-owner-full-control
          aws cloudfront create-invalidation --distribution-id E7VCQ0QQQQGSJ --paths "/*"
