name: analyse
on: [push]

jobs:
  analyse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          tools: composer:v2
      - name: Install dependencies
        working-directory: ./web
        run: composer install --prefer-dist --no-progress --optimize-autoloader
      - name: analyse
        working-directory: ./web
        run: composer analyse
